name: Depoloy to Test

on:
  push:
    branches:
      - feat/testing

env:
  DCL_PRIVATE_KEY: ${{ secrets.DCL_PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install decentraland
      run: npm i -g decentraland@latest
    - name: install npm packages
      run: |
        npm install
    - name: Build Scene
      run: | 
        npm run build:ci
    - name: Deploy Scene
      run: |
        npm run deploy:testing
